package com.sxtreh.enumeration;

public enum ParameterRuleType {
    ALL_NOT_NULL,
    //用户参数规则
    USER_REGISTER,
    USER_LOGIN,
    USER_MODIFY,

    //笔记参数规则
    NOTE_CATALOG_SAVE,
    NOTE_CATALOG_DELETE,
    NOTE_CATALOG_MODIFY,
    NOTE_CATALOG_LIST,

    NOTE_SAVE,
    NOTE_SAVE_COL,
    NOTE_DELETE,
    NOTE_DELETE_COL,
    NOTE_MODIFY,
    NOTE_COLS_MODIFY,
    NOTE_LIST,

    //网盘参数规则
    NET_DISK_FILE_LIST,
    NET_DISK_FILE_MODIFY,
    NET_DISK_FILE_DELETE,
    NET_DISK_CATALOG_SAVE,
    NET_DISK_FILE_UPLOAD,
    NET_DISK_FILE_DOWNLOAD

}
