server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: gate-way #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址
      discovery:
        cluster-name: LOCAL #集群
        namespace: d26e3a73-1ced-491e-9e0b-14a5c2de6f5c #命名空间
    gateway:
      routes:
        - id: user-service #id, 唯一
          uri: lb://user-service #lb负载均衡， 后接服务名
          predicates:
            - Path=/users/** #路由规则

        - id: note-service
          uri: lb://note-service
          predicates:
            - Path=/note/**

        - id: net-disk-service
          uri: lb://net-disk-service
          predicates:
            - Path=/netdisk/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
sxtreh:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ${sxtreh.jwt.user-secret-key}
    # 设置前端传递过来的令牌名称
    user-token-name: token