server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sxtreh.datasource.driver-class-name}
      url: jdbc:mysql://${sxtreh.datasource.host}:${sxtreh.datasource.port}/${sxtreh.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sxtreh.datasource.username}
      password: ${sxtreh.datasource.password}

  redis:
    host: ${sxtreh.redis.host}
    port: ${sxtreh.redis.port}
    database: ${sxtreh.redis.database}

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxtreh.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sxtreh:
        mapper: debug
        service: info
        controller: info

sxtreh:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: sxtreh
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token

#jwt:
#  # 设置jwt签名加密时使用的秘钥
#  user-secret-key: ${sxtreh.jwt.user-secret-key}
#  # 设置jwt过期时间
#  user-ttl: ${sxtreh.jwt.user-ttl}
#  # 设置前端传递过来的令牌名称
#  user-token-name: ${sxtreh.jwt.user-token-name}

