#禁止发布
#禁止发布
#禁止发布
sxtreh:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.1.109
    port: 3306
    database: web
    username: adminx
    password: 497852139

  redis:
    host: 192.168.1.109
    port: 6379
      #    password: 497852139
    database: 0

  multipart:
    max-file-size: 1000MB
    max-request-size: 1000MB

  jwt:
    #一天过期
    user-ttl: 86400000

  mail:
    host: smtp.qq.com
    username: 123456@qq.com
    password: 123456
    from: 123@qq.com
    to: 123456@qq.com

