#禁止发布
#禁止发布
#禁止发布
sxtreh:
  #cloud 使用nacos配置，方便热更新等
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.1.109
    port: 3306
    database: web
    username: adminx
    password: 497852139

  redis:
    host: 192.168.1.109
    port: 6379
      #    password: 497852139
    database: 0

  multipart:
    max-file-size: 10MB
    max-request-size: 100MB

  logging:
    file:
      path: ".\\Logs\\"
  jwt:
    #一天过期
    user-ttl: 86400000
    user-secret-key: sxtreh

  #windows
  netdisk:
    file:
      path:
        file: "D:\\Project\\res\\files\\"
        temp: "D:\\Project\\res\\temp\\"
        avatar: "D:\\Project\\res\\avatars\\"
        split: "\\"

  rabbitmq:
    host: 192.168.1.109
    port: 5672
    virtual-host: /
    username: adminx
    password: 497852139
